### ISSUE TITLE
Im probably doing something wrong

### ISSUE THREAD

**Issue by lIBenGravesIl** [Yolodude25/virtualbox-rich-presence#10]
Im probably doing something wrong here. but when i run main.py and open up vb, main.py wont detect im in the machine. Not sure whether thats because of the OS im running or because ive done something wrong. Is there anything i specifically have to do in config.ini?

**Comment by lIBenGravesIl** [comment]
ah just spotted "# [TODO] Add support for other operating systems". Any possibility of kali being supported in the future?

**Comment by lIBenGravesIl** [comment]
just spotted the  # [TODO] Add support for other operating systems. Any chances of seeing kali supported in the near future :D

**Comment by vidhanio** [comment]
Hey! haha thanks for the ping on this project, ive recently replaced my pc w a mac and am gonna work on adding *nix support. stay tuned! <3

**Comment by lIBenGravesIl** [comment]
Sweeeet, looking forward to it! Thank you!

**Comment by vidhanio** [comment]
Hey, could you clone and check if it works? 😄

**Comment by lIBenGravesIl** [comment]
![image](https://user-images.githubusercontent.com/61945509/135353062-1120ac68-3419-48ac-af32-d963ebfb8c5d.png)
Nope nothing.

**Comment by vidhanio** [comment]
It seems your host operating system is windows, were you talking about supporting Kali in the guest?

**Comment by lIBenGravesIl** [comment]
Apologies we were talking about different things i didnt explain myself very well. Yes I was talking about supporting kali in the guest. Im sorry I cant test to see if it works on other host operating systems.

**Comment by vidhanio** [comment]
weird... it won't show the kali linux logo, but rather should show the debian one, as that seems to be the profile you have chosen. This rich presence uses the virtualbox profile you made on creation:
![image](https://user-images.githubusercontent.com/41439633/135473387-124b459b-a080-4917-b9a0-3f2dab42ca81.png)

It is confusing that it shows that you're in menu though.

Is it possible that it thinks the machine's state is Starting rather than FirstOnline? What is the state of the VM? If it is running (as in, logged in and installed, etc.) it should show the debian state.

**Comment by vidhanio** [comment]
Hey, in f2a473b i added an option in the `config.ini` to set the Machine name, if you wanted to set that to show Kali.

**Comment by lIBenGravesIl** [comment]
Its still the same if i was logged in. It also works perfectly fine running a windows VM. I also just tried cloning and reinstalling and receive a traceback error when i run main.py 
![image](https://user-images.githubusercontent.com/61945509/135478121-502db3a0-4567-4956-966c-4bbc150d178c.png)

**Comment by vidhanio** [comment]
Make sure to create your config.ini again!

> It also works perfectly fine running a windows VM

super weird. Can you send a screenshot of what settings you used when creating the VM?

**Comment by lIBenGravesIl** [comment]
Do you want a screenshot of the description? I also remember installing it with an OVA file not an ISO, could that be a potential problem? I wanted to try a fresh install of kali since i was having problems with it already, just havent gotten round to doing it so ill be doing it regardless.

**Comment by lIBenGravesIl** [comment]
> Make sure to create your config.ini again
lol forgot works now

**Comment by vidhanio** [comment]
Works with kali?

**Comment by lIBenGravesIl** [comment]
> Works with kali?

Not yet was just saying main.py no longer gets the error. It'll be a few hours before I get the new VM installation (bad ISP downloading the ISO).

**Comment by lIBenGravesIl** [comment]
![image](https://user-images.githubusercontent.com/61945509/135530600-029005de-306b-474d-ba7b-57577103fa5b.png)
Works now with the fresh install :D. Thanks for your help mate!

**Comment by vidhanio** [comment]
No problem!! let me know if you run into any other issues. <3
