### ISSUE TITLE
Python main.py error

### ISSUE THREAD

**Issue by Treyowski** [Yolodude25/virtualbox-rich-presence#12]
C:\#######\######CENSORED######>python main.py
Traceback (most recent call last):
  File "C:\CENSORED#####\main.py", line 2, in <module>
    import virtualbox, json, pprint, configparser, time, psutil, sys
ModuleNotFoundError: No module named 'psutil'

**Comment by vidhanio** [comment]
Make sure to run `pip install -r requirements.txt` in the directory.

**Comment by Treyowski** [comment]
P:\Vbox\virtualbox-rich-presence\virtualbox-rich-presence>pip install -r requirements.txt
Requirement already satisfied: virtualbox in c:\users\Censored\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: pypresence in c:\users\Censored\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (4.2.0)
Collecting psutil
  Using cached psutil-5.8.0.tar.gz (470 kB)
Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.
Installing collected packages: psutil
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Censored\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Censored\\AppData\\Local\\Temp\\pip-install-h4nc1vvl\\psutil_855d37f573c14038b901816276693c6b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Censored\\AppData\\Local\\Temp\\pip-install-h4nc1vvl\\psutil_855d37f573c14038b901816276693c6b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Censored\AppData\Local\Temp\pip-record-lw_jq58v\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Censored\AppData\Local\Programs\Python\Python310\Include\psutil'
         cwd: C:\Users\Censored\AppData\Local\Temp\pip-install-h4nc1vvl\psutil_855d37f573c14038b901816276693c6b\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
    creating build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Censored\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Censored\\AppData\\Local\\Temp\\pip-install-h4nc1vvl\\psutil_855d37f573c14038b901816276693c6b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Censored\\AppData\\Local\\Temp\\pip-install-h4nc1vvl\\psutil_855d37f573c14038b901816276693c6b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Censored\AppData\Local\Temp\pip-record-lw_jq58v\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Censored\Python\Python310\Include\psutil' Check the logs for full command output.
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\CensoredPython\Python310\python.exe -m pip install --upgrade pip' command.

**Comment by vidhanio** [comment]
Try to install these tools and run it again:

The error message says:

error: Microsoft Visual C++ 14.0 or greater is required. Get it with
"Microsoft C++ Build Tools":
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Treyowski** [comment]
Unfortunately, I have done this before and zero response.

**Comment by vidhanio** [comment]
super weird, can you try downgrading python and see if it works? Maybe its a 3.10 bug?

**Comment by vidhanio** [comment]
Hi, any update on this? :)
