### ISSUE TITLE
python main.py error win32com

### ISSUE THREAD

**Issue by daoncrack** [Yolodude25/virtualbox-rich-presence#13]
Traceback (most recent call last):
  File "C:\Users\DaOnCrack\virtualbox-rich-presence\main.py", line 210, in <module>
    RichPresence()
  File "C:\Users\DaOnCrack\virtualbox-rich-presence\main.py", line 10, in __init__
    self.virtualbox = virtualbox.VirtualBox()
  File "C:\Users\DaOnCrack\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualbox\library_ext\vbox.py", line 22, in __init__
    manager = virtualbox.Manager()
  File "C:\Users\DaOnCrack\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualbox\__init__.py", line 163, in __init__
    self.manager = vboxapi.VirtualBoxManager(mtype, mparams)
  File "C:\Users\DaOnCrack\AppData\Local\Programs\Python\Python39\lib\site-packages\vboxapi\__init__.py", line 991, in __init__
    self.platform = PlatformMSCOM(dPlatformParams)
  File "C:\Users\DaOnCrack\AppData\Local\Programs\Python\Python39\lib\site-packages\vboxapi\__init__.py", line 427, in __init__
    from win32com import universal
ModuleNotFoundError: No module named 'win32com'

When I run it, there is no module named win32com

**Comment by vidhanio** [comment]
Could you try running:

```sh
cd <where you cloned the rich presence>
git pull
pip install -r requirements.txt
```

**Comment by daoncrack** [comment]
![image](https://user-images.githubusercontent.com/95033672/143450049-d5aedddf-ac0d-41fc-801e-e5949df8d2ac.png)
Yes I have done it 
And now problem duplicate it self

**Comment by daoncrack** [comment]
wait what version of python are u using?

**Comment by vidhanio** [comment]
That is an even weirder error. Could you try deleting the entire "virtualbox-rich-presence" directory and restarting the steps in the README again?

**Comment by daoncrack** [comment]
okay

**Comment by daoncrack** [comment]
![image](https://user-images.githubusercontent.com/95033672/143454368-ab75a85a-3722-4aa8-917a-c3ab832ceb29.png)

Please send help

**Comment by vidhanio** [comment]
Make sure to follow the config steps again (copy config.ini.example to config.ini).

**Comment by daoncrack** [comment]
ok

**Comment by daoncrack** [comment]
![image](https://user-images.githubusercontent.com/95033672/143732065-bb1d195f-9c51-4f8f-a904-31be305c8d38.png)
Yes I did it, and it appear as this

**Comment by daoncrack** [comment]
DiscordError: Error Code: 4000 Message: Invalid Client ID and how do i fix this  
![image](https://user-images.githubusercontent.com/95033672/143732132-8ad7d711-2217-40b9-be5a-7a004d6da911.png)

**Comment by vidhanio** [comment]
Did you change the config.ini? It should be working fine.

**Comment by daoncrack** [comment]
Wait Can you see if I have done my config right? 
![image](https://user-images.githubusercontent.com/95033672/143966428-29756194-983d-4356-b89c-2f1229a973ed.png)

**Comment by vidhanio** [comment]
Ah, you have misunderstood the config instruction, I think it was my fault
as they may not have been clear enough.

When you copy the config.ini, you do not have to change anything. You just
copy to the config.ini from the config.example.ini, and you leave it, as
the default settings will do everything for you.

**Comment by daoncrack** [comment]
Oh ok

**Comment by daoncrack** [comment]
Oh yes it work Thank you very much

**Comment by vidhanio** [comment]
No problem friend! Feel free to create another issue if you have any other
problems, and have a good day. :)
