### ISSUE TITLE
VB not changing states when opening a VM

### ISSUE THREAD

**Issue by vite-the-primagen** [Yolodude25/virtualbox-rich-presence#14]
i did everything correctly and its not really changing the state.

**Comment by vidhanio** [comment]
Could you send some more information? Did it log any errors?

**Comment by WaveMeow** [comment]
bump, same issue 
![image](https://user-images.githubusercontent.com/98244952/157574378-8f120658-295b-49a4-93d7-a5768eca34c7.png)

**Comment by vidhanio** [comment]
unfortunately, I can't really continue active development on this as my new Mac M1 does not work the same in regards to the vbox api. If any of you could figure out the bug/solution, you are welcome to do so, but unfortunately on my end this project is sort of archived.

**Comment by DeathHound6** [comment]
I'm having the same issue. Might look into it at some point
