### ISSUE TITLE
"Operation Unavailable" error - win32com

### ISSUE THREAD

**Issue by supraaxdd** [Yolodude25/virtualbox-rich-presence#15]
Hey,

Upon configuring the config.ini file and starting the main.py file, I get an error. The screenshot of the error can be found below:
![image](https://user-images.githubusercontent.com/54616428/152641776-31dd7a52-3b2a-434b-a40d-a38ce973d996.png)

One note, I extracted the SDK into the project root directory and ran the installer there, I wonder would that be something that could have kickstarted this issue.

Additionally, this is my config.ini:
![image](https://user-images.githubusercontent.com/54616428/152641867-9e689438-c5c1-4119-83e8-e6582f7d293f.png)

Thanks in advance!
Supra

**Comment by vidhanio** [comment]
could you try running both as non-admin in case one of them are running as
administrator?

**Comment by supraaxdd** [comment]
What do you mean by running both? `py main.py` or?

**Comment by vidhanio** [comment]
Sorry, I meant the python script and virtualbox itself. too early in the morning, haha

**Comment by supraaxdd** [comment]
Same thing is happening, regardless of whether I have it on Admin or not
