### ISSUE TITLE
VM Status not showing up

### ISSUE THREAD

**Issue by raulmllorente** [Yolodude25/virtualbox-rich-presence#16]
Hey man, first of all, you have done a great job with this RPC for Virtualbox! But sadly mine is not recognising my VM, in this case I tried with a Windows 95 VM, main.py is not crashing at all and it´s showing just my Virtualbox menu presence and not my machine status.

![imagen](https://user-images.githubusercontent.com/75579745/162794225-dfb5d203-ef3a-4df6-aace-f6392594743a.png)

I have tried to print the VirtualBox machines found list with a single line of code on the main.py and I got this single "Nougat64" machine name and it´s supposed to be a Linux system, I have no idea of what could be.

![imagen](https://user-images.githubusercontent.com/75579745/162795102-b4561730-b98b-4c41-9e56-bd86c65c6a6b.png)

But I have to say that I move my VM´s that I don´t use for a long time to a external drive to free up some disk space on my PC, so I don´t know if that could be the issue and I would need to remove the references from my VirtualBox list.

![imagen](https://user-images.githubusercontent.com/75579745/162795555-80db742d-9580-4ae7-9a09-7189d2cf808c.png)

I hope you can help me about what could be causing this issue.
Thank you!!

**Comment by raulmllorente** [comment]
Update: I don´t freaking believe it, I just remembered that Nougat was Android 6 codename, then I remembered that I had installed Bluestacks, I uninstalled it and now that error is gone, but now I have a bunch of error while executing main.py.
![imagen](https://user-images.githubusercontent.com/75579745/162931416-9c706893-f38c-4dd4-9cd2-706de2d20ea2.png)

**Comment by vidhanio** [comment]
Hi!

As mentioned in #14, I am unfortunately unable to continue maintaining this project as my new computer doesn't really use VirtualBox's API the same way. A suggestion I do have however is to try downgrading the python version to 3.6-3.7, as python is known to include breaking changes in minor versions.

**Comment by raulmllorente** [comment]
Yeah, I tried downgrading from Python 3.10 to 3.9, both x86 and x64 versions because I think it's something related to the win32com Python package dll's when the virtualbox Python package tries to interact on the virtualbox.VirtualBox() function, so I would downgrade to those Python 3.6/3.7 versions later and maybe they will work, because the virtualbox Python package last version is from 2020 though. Thank you so much for your suggestion I will try it later!!

**Comment by raulmllorente** [comment]
Sadly none of that worked so I guess I must have some issues with that library that prevents me of loading the dll's correctly. I'm closing this issue and thank you for your help man, I tried a lot of Python versions, installing twice in x64 and x86, single user and all users... But sadly I got nothing and the same dispatch error all the time.
